// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadFlow returns the embedded CollectionSpec for Flow.
func LoadFlow() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Flow: %w", err)
	}

	return spec, err
}

// LoadFlowObjects loads Flow and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FlowObjects
//	*FlowPrograms
//	*FlowMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFlowObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFlow()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FlowSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowSpecs struct {
	FlowProgramSpecs
	FlowMapSpecs
	FlowVariableSpecs
}

// FlowProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowProgramSpecs struct {
	HandleIngress *ebpf.ProgramSpec `ebpf:"handle_ingress"`
}

// FlowMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// FlowVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FlowVariableSpecs struct {
}

// FlowObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowObjects struct {
	FlowPrograms
	FlowMaps
	FlowVariables
}

func (o *FlowObjects) Close() error {
	return _FlowClose(
		&o.FlowPrograms,
		&o.FlowMaps,
	)
}

// FlowMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *FlowMaps) Close() error {
	return _FlowClose(
		m.Events,
	)
}

// FlowVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowVariables struct {
}

// FlowPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type FlowPrograms struct {
	HandleIngress *ebpf.Program `ebpf:"handle_ingress"`
}

func (p *FlowPrograms) Close() error {
	return _FlowClose(
		p.HandleIngress,
	)
}

func _FlowClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flow_bpfel.o
var _FlowBytes []byte
